# @format

apiVersion: v1
kind: Service
metadata:
  name: client-node-port-ip-service
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
